### ISSUE TITLE
We need video or at least photo updates!

### ISSUE THREAD

**Issue by davidbrown2324** [shuqin19/ice-cream#4]
@shuqin19,

We are all excited to see how the ice-cream turned out. As we cannot taste the ice-cream directly, remote collaboration is very important. **Please add some photos.**

Sincerely,
Dave

**Comment by shuqin19** [comment]
Please check the protocol, I added video and image

**Comment by davidbrown2324** [comment]
Amazing!! I think you can see how helpful this could be for our lab. And it's pretty fun.
